# Use an official Python runtime as a parent image
FROM python:3.7-alpine3.7

RUN apk update \
     && apk --no-cache add \
     bash \
     build-base \
     curl \
     gcc \
     gettext \
     git \
     libffi-dev \
     linux-headers \
     musl-dev \
     postgresql-dev \
     python3-dev \
     tini \
     libjpeg \
     zlib \
     && pip install psycopg2

RUN apk --no-cache add jpeg-dev \
         zlib-dev \
         freetype-dev \
         lcms2-dev \
         openjpeg-dev \
         tiff-dev \
         tk-dev \
         tcl-dev \
         harfbuzz-dev \
         fribidi-dev \
         redis

RUN apk update install openssh-server emacs23-nox htop screen
# For debugging
RUN apk update install sudo wget telnet tcpdump
# Man pages and "most" viewer:
RUN apk update install man most
RUN mkdir /var/run/sshd

RUN pip install pip==18.1

WORKDIR /srv/app/web/static
WORKDIR /srv/app

COPY requirements/testing.txt requirements.txt
COPY requirements/base.txt base.txt
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

ENV DJANGO_SETTINGS_MODULE='webpage.settings.test' \
     PYTHONDONTWRITEBYTECODE=1 \
     PYTHONUNBUFFERED=1

ADD entrypoint.sh .
RUN chmod +x "./entrypoint.sh"
ADD wait-for-it.sh .
RUN chmod +x "./wait-for-it.sh"

WORKDIR /srv/app
ENTRYPOINT ["bash", "entrypoint.sh"]